### ISSUE TITLE
Video indexes don't match between front end and db

### ISSUE THREAD

**Issue by KartikKapur** [Hermes-Berkeley-Org/hermes-ui#11]

**Comment by KartikKapur** [comment]
![screen shot 2018-12-30 at 6 03 43 pm](https://user-images.githubusercontent.com/17678128/50553561-e54c8580-0c5d-11e9-8d03-a7d43ded46de.png)
![screen shot 2018-12-30 at 6 03 35 pm](https://user-images.githubusercontent.com/17678128/50553563-e7aedf80-0c5d-11e9-9d4b-1a536408ed0f.png)

**Comment by ajar98** [comment]
Resolved by lecture-url-name.
